name: MacAmpApp
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    macOS: '15.0'
  xcodeVersion: '26.0'
  defaultConfig: Debug
packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    from: 0.9.0
  swift-atomics:
    url: https://github.com/apple/swift-atomics.git
    from: 1.2.0
targets:
  MacAmp:
    type: application
    platform: macOS
    deploymentTarget: '15.0'
    sources:
      - path: MacAmpApp
        excludes:
          - Info.plist
          - MacAmp.entitlements
    resources:
      - path: MacAmpApp/Skins
      - path: MacAmpApp/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hankyeomans.MacAmp
        INFOPLIST_FILE: MacAmpApp/Info.plist
        CODE_SIGN_ENTITLEMENTS: MacAmpApp/MacAmp.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: AC3LGVEJJ8
        SWIFT_VERSION: '6.0'
        PRODUCT_NAME: MacAmp
        ENABLE_HARDENED_RUNTIME: true
        SWIFT_STRICT_CONCURRENCY: complete
      configs:
        Debug:
          CODE_SIGN_IDENTITY: Apple Development
        Release:
          CODE_SIGN_IDENTITY: Developer ID Application
          CONFIGURATION_BUILD_DIR: $(PROJECT_DIR)/dist
    dependencies:
      - package: ZIPFoundation
      - package: swift-atomics
        product: Atomics
  MacAmpTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/MacAmpTests
    dependencies:
      - target: MacAmp
      - package: swift-atomics
        product: Atomics
    settings:
      base:
        SWIFT_VERSION: '6.0'
        GENERATE_INFOPLIST_FILE: true
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: AC3LGVEJJ8
schemes:
  MacAmpApp:
    build:
      targets:
        MacAmp: all
        MacAmpTests: [test]
    run:
      config: Debug
      environmentVariables:
        - variable: DYLD_INSERT_LIBRARIES
          value: ''
          isEnabled: false
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - MacAmpTests
